### PR TITLE
LPS-139942 CI test

### PR DESCRIPTION
**Pull request by markocikos**

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
Ok, https://github.com/markocikos/liferay-portal/pull/194#issuecomment-964742378 proves that `@import 'atlas-variables';` is not the issue.

I thought it might be ES6+ patterns that are introduced in the PR, because `liferay-npm-scripts` interacts with those. But we are already using both `const` and fat arrow in other plugins, so it can't be that.

I'll try installing Chromium next.

**Comment by john-co** [comment]
Not sure if I'll have any more ideas to fix/rca this. But hopefully when we find a solution let us know when ready for QA to review again.

**Comment by markocikos** [comment]
See https://github.com/liferay-frontend/liferay-portal/pull/1575#issuecomment-971835621

**Pull request closed without merging**
