### PR TITLE
LPS-139334 Text Edition Toolbar does not appear when highlighting a text in a table row

### PR DESCRIPTION
**Pull request by john-co**

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant:85fbb4bdcc3d327770f562b624d6627589a80cfb

**Comment by john-co** [comment]
Test failure doesn't seem related. It's possible that semantic versioning test batch started failing from BChan's origin/upstream. Retesting on SHA where semantic versioning test batch passed.

**Comment by john-co** [comment]
yep, also looks fixed at head now:
image

**Comment by markocikos** [comment]
Pushed the branch to https://github.com/liferay-frontend/liferay-portal/pull/1761

**Pull request closed without merging**
